services:
  - type: web
    name: quantum-devanshi
    env: python
    region: ohio
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev python3-pyaudio
      pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
      pip install gunicorn eventlet
    startCommand: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:$PORT 'main:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: RENDER
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    plan: free
