services:
  - type: web
    name: quantum-devanshi
    env: python
    region: ohio
    buildCommand: |
      pip install --upgrade pip
      pip install gunicorn eventlet
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
    plan: free

  - type: web
    name: quantum-devanshi-static
    env: static
    buildCommand: echo "Static files ready"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
