services:
  - type: web
    name: quantum-devanshi
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PIP_VERSION
        value: 24.3.1
    autoDeploy: true
    plan: free

  - type: web
    name: quantum-devanshi-static
    env: static
    buildCommand: echo "Static files ready"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
